language: python
python:
 - "3.5"
 - "3.6"
env:
 - DJANGO_VERSION=1.9.11
 - DJANGO_VERSION=1.10.3
 - DJANGO_VERSION=1.11.1
 - DJANGO_VERSION=2.0.9
 - DJANGO_VERSION=2.1.4
sudo: false
cache:
  directories:
   - $HOME/.cache/pip
install:
 - pip install -q -rrequirements/base.txt
 - pip install -q -rrequirements/tests.txt
 - pip install -q django==$DJANGO_VERSION
 - pip install coveralls
script:
 - py.test --cov-report= --cov=hamlpy hamlpy
 - flake8
after_success:
 - coveralls